<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Windows.EndpointRpc.Server</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Windows.EndpointRpc</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64;ARM64;x86;ARM32</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts\PasswordManagerLocal.Windows.EndpointRpc.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Common\Backend\PasswordManagerLocal.Common.Backend.csproj" />
    <ProjectReference Include="..\..\..\Common\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
    <ProjectReference Include="..\..\IPC\PasswordManagerLocal.Windows.Ipc.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PasswordManagerLocal.Windows.Tests.EndpointRpc" />
  </ItemGroup>
</Project>
