<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Windows.Tests.Host</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Windows.Tests.Host</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64;x86;ARM64;ARM32</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IPC\PasswordManagerLocal.Windows.Ipc.csproj" />
  </ItemGroup>
</Project>
