<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Android.Runtime</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Android.Runtime</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Backend\PasswordManagerLocal.Common.Backend.csproj" />
    <ProjectReference Include="..\..\Common\Backend.Hosting\PasswordManagerLocal.Common.Backend.Hosting.csproj" />
    <ProjectReference Include="..\..\Common\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
  </ItemGroup>
</Project>
