<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Common.Preferences</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Common.Preferences</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64;ARM64;x86;ARM32</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
  </ItemGroup>
</Project>
