<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Common.Tests</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Common.Tests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend\PasswordManagerLocal.Common.Backend.csproj" />
    <ProjectReference Include="..\Backend.Hosting\PasswordManagerLocal.Common.Backend.Hosting.csproj" />
    <ProjectReference Include="..\Frontend\PasswordManagerLocal.Common.Frontend.csproj" />
    <ProjectReference Include="..\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
    <ProjectReference Include="..\Preferences\PasswordManagerLocal.Common.Preferences.csproj" />
    <ProjectReference Include="..\..\Android\Runtime\PasswordManagerLocal.Android.Runtime.csproj" />
  </ItemGroup>
</Project>
