<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Windows.Tests.EndpointRpc</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Windows.Tests.EndpointRpc</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EndpointRpc\Contracts\PasswordManagerLocal.Windows.EndpointRpc.Contracts.csproj" />
    <ProjectReference Include="..\EndpointRpc\Client\PasswordManagerLocal.Windows.EndpointRpc.Client.csproj" />
    <ProjectReference Include="..\EndpointRpc\Server\PasswordManagerLocal.Windows.EndpointRpc.Server.csproj" />
    <ProjectReference Include="..\..\Common\Backend\PasswordManagerLocal.Common.Backend.csproj" />
    <ProjectReference Include="..\..\Common\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
    <ProjectReference Include="..\IPC\PasswordManagerLocal.Windows.Ipc.csproj" />
  </ItemGroup>
</Project>
