namespace PasswordManagerLocal.Windows.Ipc.Contracts;

public enum IpcErrorCode
{
    ProtocolViolation = 1,
    UnsupportedProtocolVersion = 2,
    HandshakeRequired = 3,
    DuplicateHandshake = 4,
    UnexpectedPeerRole = 5,
    UnknownOperation = 6,
    InvalidEnvelope = 7,
    InvalidPayload = 8,
    HandlerFailed = 9,
    RequestCancelled = 10,
    ConnectionClosed = 11,
    UiAlreadyRegistered = 12,
    RequestRejected = 13,
    InternalFailure = 14,
    UnsupportedCapability = 15,
    ServerBusy = 16,
    TooManyRequests = 17,
    RequestPayloadTooLarge = 18,
    ResponsePayloadTooLarge = 19,
    SerializedEnvelopeTooLarge = 20,
    AgentStopping = 21,
    UiNotRegistered = 22,
    UiActivationUnavailable = 23,
    UiActivationRejected = 24,
    UiExecutableNotFound = 25,
    UiLaunchFailed = 26,
    UnauthorizedOperation = 27,
    TooManyConnections = 28,
    AgentUnavailable = 29,
    UiActivationFailed = 30
}
