<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Common.Frontend</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Common.Frontend</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Platforms>AnyCPU;x64;x86;ARM64;ARM32</Platforms>
  </PropertyGroup>


  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="ReactiveUI.Avalonia" />

    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="ZXing.Net" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
    <ProjectReference Include="..\Preferences\PasswordManagerLocal.Common.Preferences.csproj" />
  </ItemGroup>
</Project>
