using PasswordManagerLocal.Windows.EndpointRpc.Contracts;
using PasswordManagerLocal.Windows.EndpointRpc.Contracts.Requests;
using PasswordManagerLocal.Windows.EndpointRpc.Contracts.LargeTransfer;
using PasswordManagerLocal.Windows.EndpointRpc.Contracts.Responses;
using System.Text.Json.Serialization;

namespace PasswordManagerLocal.Windows.EndpointRpc.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow)]
[JsonSerializable(typeof(EndpointRpcError))]
[JsonSerializable(typeof(EndpointRecoveryMetadata))]
[JsonSerializable(typeof(EndpointLargeResultDescriptor))]
[JsonSerializable(typeof(GetEndpointLargeResultChunkRequest))]
[JsonSerializable(typeof(GetEndpointLargeResultChunkResponse))]
[JsonSerializable(typeof(ReleaseEndpointLargeResultRequest))]
[JsonSerializable(typeof(ReleaseEndpointLargeResultResponse))]
[JsonSerializable(typeof(RegisterEndpointRequest))]
[JsonSerializable(typeof(LoginEndpointRequest))]
[JsonSerializable(typeof(RenewAuthSessionEndpointRequest))]
[JsonSerializable(typeof(LogoutEndpointRequest))]
[JsonSerializable(typeof(GetAuthSessionStatusEndpointRequest))]
[JsonSerializable(typeof(ChangeMasterPasswordEndpointRequest))]
[JsonSerializable(typeof(GetUserProfileInfoEndpointRequest))]
[JsonSerializable(typeof(DeleteUserAccountEndpointRequest))]
[JsonSerializable(typeof(ChangeUsernameEndpointRequest))]
[JsonSerializable(typeof(UpdateUserProfileInfoEndpointRequest))]
[JsonSerializable(typeof(GetLocalDeviceInfoEndpointRequest))]
[JsonSerializable(typeof(GetLocalUserSyncOnEndpointRequest))]
[JsonSerializable(typeof(SetLocalUserSyncOnEndpointRequest))]
[JsonSerializable(typeof(SetLocalDeviceNameEndpointRequest))]
[JsonSerializable(typeof(GetUserDevicesEndpointRequest))]
[JsonSerializable(typeof(SetUserDeviceNameEndpointRequest))]
[JsonSerializable(typeof(SetUserDeviceSyncOnEndpointRequest))]
[JsonSerializable(typeof(UnblockUserDeviceEndpointRequest))]
[JsonSerializable(typeof(DisconnectUserDeviceEndpointRequest))]
[JsonSerializable(typeof(StartDeviceEnrollmentEndpointRequest))]
[JsonSerializable(typeof(GetDeviceEnrollmentStatusEndpointRequest))]
[JsonSerializable(typeof(CancelDeviceEnrollmentEndpointRequest))]
[JsonSerializable(typeof(AddDeviceByCodeEndpointRequest))]
[JsonSerializable(typeof(RestoreRememberedSessionsEndpointRequest))]
[JsonSerializable(typeof(InitializeRememberMeSessionEndpointRequest))]
[JsonSerializable(typeof(SetRememberMeEndpointRequest))]
[JsonSerializable(typeof(GetSavedPasswordsEndpointRequest))]
[JsonSerializable(typeof(AddNewPasswordEndpointRequest))]
[JsonSerializable(typeof(RemovePasswordsEndpointRequest))]
[JsonSerializable(typeof(GetUnsecurePasswordEndpointRequest))]
[JsonSerializable(typeof(UpdatePasswordEndpointRequest))]
[JsonSerializable(typeof(ExportPasswordsToUserEndpointRequest))]
[JsonSerializable(typeof(AddCustomUserColorsEndpointRequest))]
[JsonSerializable(typeof(DeleteCustomUserColorsEndpointRequest))]
[JsonSerializable(typeof(ExportCustomUserColorsToUserEndpointRequest))]
[JsonSerializable(typeof(UpdateCustomUserColorEndpointRequest))]
[JsonSerializable(typeof(AddPasswordTagEndpointRequest))]
[JsonSerializable(typeof(DeletePasswordTagEndpointRequest))]
[JsonSerializable(typeof(ExportPasswordTagsToUserEndpointRequest))]
[JsonSerializable(typeof(UpdatePasswordTagEndpointRequest))]
[JsonSerializable(typeof(RegisterEndpointResponse))]
[JsonSerializable(typeof(LoginEndpointResponse))]
[JsonSerializable(typeof(RenewAuthSessionEndpointResponse))]
[JsonSerializable(typeof(LogoutEndpointResponse))]
[JsonSerializable(typeof(GetAuthSessionStatusEndpointResponse))]
[JsonSerializable(typeof(ChangeMasterPasswordEndpointResponse))]
[JsonSerializable(typeof(GetUserProfileInfoEndpointResponse))]
[JsonSerializable(typeof(DeleteUserAccountEndpointResponse))]
[JsonSerializable(typeof(ChangeUsernameEndpointResponse))]
[JsonSerializable(typeof(UpdateUserProfileInfoEndpointResponse))]
[JsonSerializable(typeof(GetLocalDeviceInfoEndpointResponse))]
[JsonSerializable(typeof(GetLocalUserSyncOnEndpointResponse))]
[JsonSerializable(typeof(SetLocalUserSyncOnEndpointResponse))]
[JsonSerializable(typeof(SetLocalDeviceNameEndpointResponse))]
[JsonSerializable(typeof(GetUserDevicesEndpointResponse))]
[JsonSerializable(typeof(SetUserDeviceNameEndpointResponse))]
[JsonSerializable(typeof(SetUserDeviceSyncOnEndpointResponse))]
[JsonSerializable(typeof(UnblockUserDeviceEndpointResponse))]
[JsonSerializable(typeof(DisconnectUserDeviceEndpointResponse))]
[JsonSerializable(typeof(StartDeviceEnrollmentEndpointResponse))]
[JsonSerializable(typeof(GetDeviceEnrollmentStatusEndpointResponse))]
[JsonSerializable(typeof(CancelDeviceEnrollmentEndpointResponse))]
[JsonSerializable(typeof(AddDeviceByCodeEndpointResponse))]
[JsonSerializable(typeof(RestoreRememberedSessionsEndpointResponse))]
[JsonSerializable(typeof(InitializeRememberMeSessionEndpointResponse))]
[JsonSerializable(typeof(SetRememberMeEndpointResponse))]
[JsonSerializable(typeof(GetSavedPasswordsEndpointResponse))]
[JsonSerializable(typeof(AddNewPasswordEndpointResponse))]
[JsonSerializable(typeof(RemovePasswordsEndpointResponse))]
[JsonSerializable(typeof(GetUnsecurePasswordEndpointResponse))]
[JsonSerializable(typeof(UpdatePasswordEndpointResponse))]
[JsonSerializable(typeof(ExportPasswordsToUserEndpointResponse))]
[JsonSerializable(typeof(AddCustomUserColorsEndpointResponse))]
[JsonSerializable(typeof(DeleteCustomUserColorsEndpointResponse))]
[JsonSerializable(typeof(ExportCustomUserColorsToUserEndpointResponse))]
[JsonSerializable(typeof(UpdateCustomUserColorEndpointResponse))]
[JsonSerializable(typeof(AddPasswordTagEndpointResponse))]
[JsonSerializable(typeof(DeletePasswordTagEndpointResponse))]
[JsonSerializable(typeof(ExportPasswordTagsToUserEndpointResponse))]
[JsonSerializable(typeof(UpdatePasswordTagEndpointResponse))]
public partial class EndpointRpcJsonContext : JsonSerializerContext
{
}
