<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Android.Backend</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Android.Backend</RootNamespace>
    <TargetFramework>net10.0-android36.0</TargetFramework>
    <SupportedOSPlatformVersion>29</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;ARM64;ARM32</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Backend\PasswordManagerLocal.Common.Backend.csproj" />
    <ProjectReference Include="..\..\Common\Backend.Hosting\PasswordManagerLocal.Common.Backend.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
  </ItemGroup>

</Project>
