<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Common.Backend</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Common.Backend</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;ARM64;x86;ARM32</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="NSec.Cryptography" />
  </ItemGroup>


  <ItemGroup>
    <Protobuf Include="Sync\Sync.proto" GrpcServices="None" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
  </ItemGroup>

</Project>