namespace PasswordManagerLocal.Windows.EndpointRpc.Contracts;

public enum EndpointOperationId
{
    Register = 1,
    Login = 2,
    RenewAuthSession = 3,
    Logout = 4,
    GetAuthSessionStatus = 5,
    ChangeMasterPassword = 6,
    GetUserProfileInfo = 7,
    DeleteUserAccount = 8,
    ChangeUsername = 9,
    UpdateUserProfileInfo = 10,
    GetLocalDeviceInfo = 11,
    GetLocalUserSyncOn = 12,
    SetLocalUserSyncOn = 13,
    SetLocalDeviceName = 14,
    GetUserDevices = 15,
    SetUserDeviceName = 16,
    SetUserDeviceSyncOn = 17,
    UnblockUserDevice = 18,
    DisconnectUserDevice = 19,
    StartDeviceEnrollment = 20,
    GetDeviceEnrollmentStatus = 21,
    CancelDeviceEnrollment = 22,
    AddDeviceByCode = 23,
    RestoreRememberedSessions = 24,
    InitializeRememberMeSession = 25,
    SetRememberMe = 26,
    GetSavedPasswords = 27,
    AddNewPassword = 28,
    RemovePasswords = 29,
    GetUnsecurePassword = 30,
    UpdatePassword = 31,
    ExportPasswordsToUser = 32,
    AddCustomUserColors = 33,
    DeleteCustomUserColors = 34,
    ExportCustomUserColorsToUser = 35,
    UpdateCustomUserColor = 36,
    AddPasswordTag = 37,
    DeletePasswordTag = 38,
    ExportPasswordTagsToUser = 39,
    UpdatePasswordTag = 40,
}
