<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Windows.Backend</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Windows.Backend</RootNamespace>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64;ARM64;x86;ARM32</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Backend\PasswordManagerLocal.Common.Backend.csproj" />
    <ProjectReference Include="..\..\Common\Backend.Hosting\PasswordManagerLocal.Common.Backend.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
  </ItemGroup>

</Project>
