<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Common.Contracts</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Common.Contracts</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64;ARM64;x86;ARM32</Platforms>
  </PropertyGroup>
</Project>
